import React, { useState, useEffect, useMemo, useRef } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { 
  Settings2, Palette, Sparkles, Bell, Shield, Database, HelpCircle, 
  Search, Sliders, Moon, Sun, Monitor, Type, Info, Key, LogOut, Trash2, 
  ShieldAlert, Cloud, FileText, Check, AlertTriangle, 
  ChevronRight, Volume2, Globe, Calendar, Clock, Laptop, Eye, Heart, Download,
  Bug, MessageSquare, BookOpen, Star, Send, Paperclip, CheckCircle2, MessageCircle,
  Award, ShieldCheck, ChevronDown, RefreshCw, Smartphone, Lock, Mail, Menu
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { usePersonalization } from '../context/PersonalizationContext';
import { useTheme } from '../context/ThemeContext';
import { useLanguage } from '../context/LanguageContext';
import { getUserData, userData } from '../userStore/userData';
import { useRecoilState } from 'recoil';
import toast from 'react-hot-toast';
import axios from 'axios';
import { API, apis } from '../types';

const CATEGORIES = [
  { id: 'general', label: 'General', icon: Sliders, description: 'Basic application & jurisdiction preferences.' },
  { id: 'appearance', label: 'Appearance', icon: Palette, description: 'Customize UI themes and layout density.' },
  { id: 'notifications', label: 'Notifications', icon: Bell, description: 'Manage hearing alerts and AI updates.' },
  { id: 'security', label: 'Security & Privacy', icon: Shield, description: 'Protect your advocate account & credentials.' },
  { id: 'help', label: 'Help & App Guide', icon: HelpCircle, description: 'Interactive App Guide, FAQs & Support.' }
];

const FAQ_DATA = [
  {
    category: 'AI Legal Assistant',
    question: 'How do I prompt the AI Assistant for legal research & precedents?',
    answer: "Use natural legal language. For example: 'Find Supreme Court judgments on Section 302 IPC regarding circumstantial evidence' or 'Draft a legal notice reply for breach of contract'."
  },
  {
    category: 'My Matters & Workspace',
    question: 'Can I invite junior advocates or team members to my cases?',
    answer: "Yes, you can invite team members to collaborate on specific case folders, upload evidence, and share strategic notes in real-time."
  },
  {
    category: 'Document Indexing',
    question: 'How do I upload court documents or opposition filings?',
    answer: "Navigate to the Case Workspace, click 'Upload Document', and choose PDF or Word files. The system automatically performs high-precision OCR and indexes them for AI search."
  },
  {
    category: 'Legal Research Index',
    question: 'Is the judgment database updated with recent High Court & SC rulings?',
    answer: "Yes, our search engine indexes judgments and legal precedents continuously, ensuring you get the latest rulings from Indian High Courts and the Supreme Court."
  },
  {
    category: 'Draft Maker Tool',
    question: 'Can I export generated notices and petitions directly to MS Word?',
    answer: "Yes. All legal drafts and notices generated by AI LEGAL can be downloaded as Word documents (.docx) or PDF files with clean court formatting."
  },
  {
    category: 'Evidence Analyst',
    question: 'What file formats are supported by the Evidence Analyst?',
    answer: "It supports PDF, DOCX, TXT, and scanned image files (PNG, JPG). Scanned documents automatically undergo high-accuracy legal OCR."
  },
  {
    category: 'Security & Password',
    question: 'How do I change my password or manage active sessions?',
    answer: "Go to Settings > Security & Privacy. You can update your password, enable 2FA, or log out of all active devices with a single click."
  },
  {
    category: 'Subscription & Plans',
    question: 'What features are included in the Advocate Pro Plan?',
    answer: "The Pro Plan offers unlimited AI Assistant queries, priority document OCR indexing, advanced notice templates, and multi-device trusted sessions."
  }
];

const GUIDE_TOPICS = [
  {
    id: 'drafting',
    title: 'How to Draft Legal Notices & Contracts',
    icon: FileText,
    summary: 'Step-by-step guide to generating court-ready notices, petitions, and commercial agreements.',
    steps: [
      'Navigate to AI Tools > Legal Notice & Agreement Drafter.',
      'Select your document type (e.g. Eviction Notice, Recovery Notice, Commercial NDA).',
      'Fill in the client details, respondent details, and core cause of action.',
      'Click "Generate Draft with AI" to preview the formatted legal draft.',
      'Export directly to MS Word (.docx) or PDF.'
    ]
  },
  {
    id: 'research',
    title: 'How to Conduct Deep Judgment Research',
    icon: Search,
    summary: 'Search Supreme Court & High Court precedents with citation analysis.',
    steps: [
      'Go to AI Tools > Legal Research & Precedent Finder.',
      'Type your legal issue or ratio decidendi prompt (e.g. "bail in NDPS commercial quantity").',
      'Filter results by Jurisdiction (Supreme Court / Delhi High Court / Bombay High Court).',
      'Copy citations or bookmark judgments to your Case Workspace.'
    ]
  },
  {
    id: 'evidence',
    title: 'How to Analyze Evidence & Charge Sheets',
    icon: Shield,
    summary: 'Upload scanned FIRs, affidavits, and exhibits for automated AI extraction.',
    steps: [
      'Open your Case Workspace or navigate to Evidence Analyst.',
      'Upload PDFs, scanned images, or opposition counter-affidavits.',
      'AI automatically extracts key dates, contradiction points, and exhibit summaries.',
      'Ask specific questions to the AI about the uploaded evidence files.'
    ]
  },
  {
    id: 'workspace',
    title: 'How to Organize Case Folders & Court Diary',
    icon: Calendar,
    summary: 'Manage daily cause lists, hearing dates, and court client files.',
    steps: [
      'Create a new Matter/Case under "My Matters".',
      'Add next hearing dates, court hall number, and presiding judge details.',
      'Set automated 24-hour hearing reminders via SMS/Email.',
      'Attach all relevant client pleadings in the dedicated case drive.'
    ]
  }
];

const SettingsPage = () => {
  const navigate = useNavigate();
  const [currentUserData] = useRecoilState(userData);
  const user = currentUserData.user || getUserData() || { name: 'Advocate', email: 'aditi@uwo24.com' };
  const { personalizations, updatePersonalization, resetPersonalizations } = usePersonalization();
  const { theme, setTheme } = useTheme();
  
  // Active Category State
  const [activeCategory, setActiveCategory] = useState('general');
  const [searchQuery, setSearchQuery] = useState('');
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  
  // Help & Support Sub-tab state
  const [helpSubTab, setHelpSubTab] = useState('guide'); // 'guide' | 'faqs' | 'bug' | 'feature' | 'contact'
  
  // App Guide Interactive State
  const [selectedGuideTopic, setSelectedGuideTopic] = useState(GUIDE_TOPICS[0]);
  const [guideQuery, setGuideQuery] = useState('');
  const [guideChat, setGuideChat] = useState([
    { sender: 'ai', text: 'Hello Counselor! 👋 Welcome to the AI LEGAL App Guide. How can I assist you with using the platform today?' }
  ]);
  const [isGuideThinking, setIsGuideThinking] = useState(false);

  // FAQ Accordion State
  const [expandedFaqIndex, setExpandedFaqIndex] = useState(null);
  const [faqSearch, setFaqSearch] = useState('');

  // Bug Report Form
  const [bugForm, setBugForm] = useState({ title: '', description: '', tool: 'General App', screenshot: null });
  const [submittingBug, setSubmittingBug] = useState(false);

  // Feature Request Form
  const [featureForm, setFeatureForm] = useState({ title: '', category: 'AI Assistant', description: '', benefit: '' });
  const [submittingFeature, setSubmittingFeature] = useState(false);

  // Security Form States
  const [passwordForm, setPasswordForm] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });
  const [recoveryEmail, setRecoveryEmail] = useState('');
  const [twoFactor, setTwoFactor] = useState(false);

  // Dialog State
  const [dialogConfig, setDialogConfig] = useState({ show: false, type: '', title: '', desc: '', action: null });

  // General Settings State bindings
  const generalSettings = useMemo(() => personalizations?.general || {}, [personalizations]);
  const notifPrefs = useMemo(() => personalizations?.notifications || {}, [personalizations]);
  const personalizationPrefs = useMemo(() => personalizations?.personalization || {}, [personalizations]);

  // Sync state values on load
  useEffect(() => {
    if (personalizations?.security) {
      setRecoveryEmail(personalizations.security.recoveryEmail || '');
      setTwoFactor(personalizations.security.twoFactor || false);
    }
  }, [personalizations]);

  // Filter Categories
  const filteredCategories = useMemo(() => {
    if (!searchQuery) return CATEGORIES;
    return CATEGORIES.filter(cat => 
      cat.label.toLowerCase().includes(searchQuery.toLowerCase()) ||
      cat.description.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [searchQuery]);

  // Filter FAQs
  const filteredFaqs = useMemo(() => {
    if (!faqSearch) return FAQ_DATA;
    const q = faqSearch.toLowerCase();
    return FAQ_DATA.filter(f => f.question.toLowerCase().includes(q) || f.answer.toLowerCase().includes(q) || f.category.toLowerCase().includes(q));
  }, [faqSearch]);

  // Helpers
  const handleToggle = async (section, key, currentValue) => {
    try {
      const targetValue = !currentValue;
      await updatePersonalization(section, { [key]: targetValue });
      toast.success('Setting updated instantly! ⚡');
    } catch (e) {
      toast.error('Failed to update setting.');
    }
  };

  const handleSelectChange = async (section, key, value) => {
    try {
      await updatePersonalization(section, { [key]: value });
      toast.success('Preferences saved successfully!');
    } catch (e) {
      toast.error('Failed to save preferences.');
    }
  };

  const triggerConfirm = (type, title, desc, action) => {
    setDialogConfig({ show: true, type, title, desc, action });
  };

  const handleResetAll = async () => {
    await resetPersonalizations();
    toast.success('All settings reset to defaults.');
    setDialogConfig({ show: false, type: '', title: '', desc: '', action: null });
  };

  const handleUpdatePassword = async (e) => {
    e.preventDefault();
    if (!passwordForm.currentPassword || !passwordForm.newPassword || !passwordForm.confirmPassword) {
      toast.error('Please fill in all password fields.');
      return;
    }
    if (passwordForm.newPassword !== passwordForm.confirmPassword) {
      toast.error('Passwords do not match.');
      return;
    }
    const loadingToast = toast.loading('Updating password...');
    try {
      await axios.put(`${API}/user/change-password`, {
        currentPassword: passwordForm.currentPassword,
        newPassword: passwordForm.newPassword
      }, {
        headers: { 'Authorization': `Bearer ${user.token}` }
      });
      toast.dismiss(loadingToast);
      toast.success('Password updated successfully!');
      setPasswordForm({ currentPassword: '', newPassword: '', confirmPassword: '' });
    } catch (err) {
      toast.dismiss(loadingToast);
      toast.error(err.response?.data?.error || 'Failed to change password. Please check current password.');
    }
  };

  const handleSendGuideMessage = (textToSend) => {
    const query = textToSend || guideQuery;
    if (!query.trim()) return;

    setGuideChat(prev => [...prev, { sender: 'user', text: query }]);
    setGuideQuery('');
    setIsGuideThinking(true);

    setTimeout(() => {
      let reply = "I can guide you! To use this feature, open the left navigation panel, select your target workspace tool, and follow the step-by-step assistant instructions.";
      const lower = query.toLowerCase();
      if (lower.includes('draft') || lower.includes('notice') || lower.includes('contract')) {
        reply = "For Drafting: Go to 'AI Tools' > 'Legal Notice & Agreement Drafter'. Choose your desired template (e.g. Legal Notice, NDA, Petition), enter the client details, and click 'Generate Draft'. You can export as .docx or PDF anytime.";
      } else if (lower.includes('research') || lower.includes('case law') || lower.includes('judgment')) {
        reply = "For Research: Open 'AI Tools' > 'Legal Research & Precedents'. Type your legal topic or section query (e.g. 'NDPS bail precedent Supreme Court'). View cited judgments with instant ratio analysis.";
      } else if (lower.includes('evidence') || lower.includes('ocr') || lower.includes('fir')) {
        reply = "For Evidence Analysis: Open your Case Workspace or 'Evidence Analyst'. Click 'Upload Document' to attach scanned FIRs or affidavits. AI LEGAL will perform high-precision OCR and highlight contradicting statements.";
      } else if (lower.includes('setting') || lower.includes('theme') || lower.includes('dark')) {
        reply = "For Settings & Themes: Use Settings > Appearance to toggle Dark Mode / Light Mode or change font scales. Use Settings > Security to manage active sessions and passwords.";
      }

      setGuideChat(prev => [...prev, { sender: 'ai', text: reply }]);
      setIsGuideThinking(false);
    }, 600);
  };

  const handleBugSubmit = (e) => {
    e.preventDefault();
    if (!bugForm.title || !bugForm.description) {
      toast.error('Please provide a title and description.');
      return;
    }
    setSubmittingBug(true);
    setTimeout(() => {
      toast.success('Bug report submitted! Our engineering team will review it. 🐞');
      setBugForm({ title: '', description: '', tool: 'General App', screenshot: null });
      setSubmittingBug(false);
    }, 800);
  };

  const handleFeatureSubmit = (e) => {
    e.preventDefault();
    if (!featureForm.title || !featureForm.description) {
      toast.error('Please complete the feature request fields.');
      return;
    }
    setSubmittingFeature(true);
    setTimeout(() => {
      toast.success('Feature request submitted! Thank you for helping shape AI LEGAL. 💡');
      setFeatureForm({ title: '', category: 'AI Assistant', description: '', benefit: '' });
      setSubmittingFeature(false);
    }, 800);
  };

  return (
    <div className="min-h-full bg-[#F8FAFC] dark:bg-[#0F172A] flex flex-col font-sans select-text p-4 sm:p-6 lg:p-8 text-slate-900 dark:text-white transition-colors duration-200">
      
      {/* Settings Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-6 border-b border-slate-200 dark:border-slate-800 shrink-0">
        <div>
          <div className="flex items-center gap-2 font-black">
            <div className="w-8 h-8 rounded-xl bg-[#C8A34D]/15 border border-[#C8A34D]/30 flex items-center justify-center text-[#C8A34D] shrink-0">
              <Settings2 size={18} />
            </div>
            <h1 className="text-xl sm:text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight truncate">AI LEGAL System Settings</h1>
          </div>
          <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 mt-1">Configure workspace parameters, app guide, security, and appearance settings.</p>
        </div>
        <div className="relative w-full sm:w-80">
          <Search className="absolute left-3.5 top-3 w-4 h-4 text-[#C8A34D]" />
          <input
            type="text"
            placeholder="Search settings category..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-bold bg-white dark:bg-[#1E293B] focus:outline-none focus:border-[#C8A34D] transition-all placeholder-slate-400 text-slate-900 dark:text-white shadow-xs"
          />
        </div>
      </div>

      {/* Main Grid */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-4 gap-8 pt-8 items-start">
        
        {/* Left Sidebar Categories */}
        <div className={`lg:col-span-1 space-y-2 transition-all ${isSidebarCollapsed ? 'hidden lg:block lg:w-16' : 'w-full'}`}>
          <div className="flex items-center justify-between px-2 mb-2 lg:mb-3">
            <span className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest">Settings Console</span>
            <button 
              onClick={() => setIsSidebarCollapsed(!isSidebarCollapsed)}
              className="hidden lg:block text-[9px] font-extrabold text-[#C8A34D] hover:underline cursor-pointer"
            >
              {isSidebarCollapsed ? 'Expand' : 'Collapse'}
            </button>
          </div>
          {filteredCategories.map(cat => {
            const Icon = cat.icon;
            const isActive = activeCategory === cat.id;
            return (
              <button
                key={cat.id}
                onClick={() => setActiveCategory(cat.id)}
                className={`w-full flex items-center gap-3.5 px-4 py-3 rounded-xl text-left transition-all cursor-pointer ${
                  isActive 
                    ? 'bg-[#C8A34D]/15 text-[#B48A35] dark:text-[#C8A34D] font-extrabold border border-[#C8A34D]/40 shadow-xs'
                    : 'bg-white dark:bg-[#1E293B] text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200/70 dark:border-slate-800 font-semibold'
                }`}
              >
                <Icon className={`w-4 h-4 shrink-0 ${isActive ? 'text-[#C8A34D]' : 'text-slate-400 dark:text-slate-500'}`} />
                {!isSidebarCollapsed && (
                  <div className="min-w-0 flex-1">
                    <p className="text-xs truncate leading-none font-bold">{cat.label}</p>
                  </div>
                )}
              </button>
            );
          })}
        </div>

        {/* Right Content Panel */}
        <div className="lg:col-span-3 bg-white dark:bg-[#1E293B] border border-slate-200/80 dark:border-slate-800 rounded-2xl p-6 sm:p-8 shadow-[0_4px_20px_rgba(0,0,0,0.03)] dark:shadow-none space-y-8 min-h-[520px]">
          
          {/* CATEGORY 1: GENERAL SETTINGS */}
          {activeCategory === 'general' && (
            <div className="space-y-6 animate-fade-in">
              <div>
                <h3 className="text-xs font-black uppercase tracking-widest text-[#C8A34D] border-b border-slate-100 dark:border-slate-800 pb-3 flex items-center gap-2">
                  <Sliders size={14} /> General Settings & Jurisdiction
                </h3>
                <p className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 mt-2">Adjust core application defaults, languages, and time preferences.</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2">
                {/* Default Dashboard */}
                <div>
                  <label className="text-[10px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1.5">Default Workspace View</label>
                  <select
                    value={generalSettings.defaultDashboard || '/dashboard'}
                    onChange={(e) => handleSelectChange('general', 'defaultDashboard', e.target.value)}
                    className="w-full bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D] transition-all cursor-pointer"
                  >
                    <option value="/dashboard">Main Dashboard</option>
                    <option value="/dashboard/chat/new">AI Legal Assistant</option>
                    <option value="/dashboard/cases">My Matters / Case Files</option>
                    <option value="/dashboard/tools">AI Litigation Tools</option>
                  </select>
                </div>

                {/* Primary Language */}
                <div>
                  <label className="text-[10px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1.5">Language Preference</label>
                  <select
                    value={generalSettings.language || 'English'}
                    onChange={(e) => handleSelectChange('general', 'language', e.target.value)}
                    className="w-full bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D] transition-all cursor-pointer"
                  >
                    <option value="English">English</option>
                    <option value="Hindi">Hindi (हिंदी)</option>
                    <option value="Bilingual">Bilingual (English & Hindi)</option>
                    <option value="Marathi">Marathi (मराठी)</option>
                    <option value="Gujarati">Gujarati (ગુજરાતી)</option>
                    <option value="Bengali">Bengali (বাংলা)</option>
                  </select>
                </div>

                {/* Default Court Jurisdiction */}
                <div>
                  <label className="text-[10px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1.5">Default Court Jurisdiction</label>
                  <select
                    value={generalSettings.jurisdiction || 'Supreme Court of India'}
                    onChange={(e) => handleSelectChange('general', 'jurisdiction', e.target.value)}
                    className="w-full bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D] transition-all cursor-pointer"
                  >
                    <option value="Supreme Court of India">Supreme Court of India</option>
                    <option value="High Court of Delhi">High Court of Delhi</option>
                    <option value="High Court of Bombay">High Court of Bombay</option>
                    <option value="High Court of Judicature at Allahabad">High Court of Judicature at Allahabad</option>
                    <option value="District & Sessions Courts">District & Sessions Courts</option>
                  </select>
                </div>

                {/* Time Zone */}
                <div>
                  <label className="text-[10px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1.5">Time Zone</label>
                  <select
                    value={generalSettings.timeZone || 'IST'}
                    onChange={(e) => handleSelectChange('general', 'timeZone', e.target.value)}
                    className="w-full bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D] transition-all cursor-pointer"
                  >
                    <option value="IST">India Standard Time (IST) - GMT+5:30</option>
                    <option value="UTC">Coordinated Universal Time (UTC)</option>
                  </select>
                </div>

                {/* Date Format */}
                <div>
                  <label className="text-[10px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1.5">Date Format</label>
                  <select
                    value={generalSettings.dateFormat || 'DD/MM/YYYY'}
                    onChange={(e) => handleSelectChange('general', 'dateFormat', e.target.value)}
                    className="w-full bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D] transition-all cursor-pointer"
                  >
                    <option value="DD/MM/YYYY">DD / MM / YYYY (e.g. 14/08/2026)</option>
                    <option value="MM/DD/YYYY">MM / DD / YYYY (e.g. 08/14/2026)</option>
                    <option value="YYYY-MM-DD">YYYY - MM - DD (e.g. 2026-08-14)</option>
                  </select>
                </div>

                {/* Auto Save Toggle */}
                <div className="flex items-center justify-between p-4 border border-slate-200 dark:border-slate-800 rounded-xl bg-slate-50/50 dark:bg-[#0F172A]">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800 dark:text-white">Auto-Save Drafts</h4>
                    <p className="text-[10px] font-semibold text-slate-400 mt-0.5">Automatically save legal notices & notes every 30 seconds.</p>
                  </div>
                  <button 
                    onClick={() => handleToggle('general', 'autoSave', generalSettings.autoSave !== false)}
                    className={`w-10 h-5 rounded-full p-0.5 transition-all duration-300 ${generalSettings.autoSave !== false ? 'bg-[#C8A34D]' : 'bg-slate-300 dark:bg-slate-700'}`}
                  >
                    <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 ${generalSettings.autoSave !== false ? 'translate-x-5' : 'translate-x-0'}`} />
                  </button>
                </div>
              </div>

              {/* Reset Section */}
              <div className="border-t border-slate-100 dark:border-slate-800 pt-6 flex items-center justify-between flex-wrap gap-4">
                <div>
                  <h4 className="text-xs font-bold text-rose-500">Restore Default Settings</h4>
                  <p className="text-[10px] font-semibold text-slate-400 mt-0.5">Reset all general, theme, and notification configurations back to default.</p>
                </div>
                <button
                  onClick={() => triggerConfirm('reset', 'Reset All Settings', 'Are you sure you want to restore all general, appearance, and notifications configurations to default?', handleResetAll)}
                  className="px-4 py-2 bg-rose-50 dark:bg-rose-950/40 hover:bg-rose-100 dark:hover:bg-rose-900/60 text-rose-600 dark:text-rose-400 rounded-xl text-xs font-black uppercase tracking-wider border border-rose-100 dark:border-rose-900/50 transition-colors cursor-pointer"
                >
                  Restore Defaults
                </button>
              </div>
            </div>
          )}

          {/* CATEGORY 2: APPEARANCE SETTINGS */}
          {activeCategory === 'appearance' && (
            <div className="space-y-6 animate-fade-in">
              <div>
                <h3 className="text-xs font-black uppercase tracking-widest text-[#C8A34D] border-b border-slate-100 dark:border-slate-800 pb-3 flex items-center gap-2">
                  <Palette size={14} /> Appearance & Layout Customization
                </h3>
                <p className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 mt-2">Personalize workspace themes, font sizing, and visual density.</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2">
                {/* Theme Mode */}
                <div>
                  <label className="text-[10px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1.5">Theme Mode</label>
                  <select
                    value={theme}
                    onChange={(e) => {
                      setTheme(e.target.value);
                      handleSelectChange('general', 'theme', e.target.value);
                    }}
                    className="w-full bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D] transition-all cursor-pointer"
                  >
                    <option value="light">☀️ Light Mode</option>
                    <option value="dark">🌙 Dark Mode (Luxury Dark)</option>
                    <option value="system">🖥️ System Default</option>
                  </select>
                </div>

                {/* Font Size */}
                <div>
                  <label className="text-[10px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1.5">Font Scale</label>
                  <select
                    value={personalizationPrefs.fontSize || 'Medium'}
                    onChange={(e) => handleSelectChange('personalization', 'fontSize', e.target.value)}
                    className="w-full bg-white dark:bg-[#0F172A] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D] transition-all cursor-pointer"
                  >
                    <option value="Small">Small (Compact Legal Text)</option>
                    <option value="Medium">Medium (Standard Court Standard)</option>
                    <option value="Large">Large (High Contrast)</option>
                  </select>
                </div>
              </div>

              {/* Toggles */}
              <div className="border-t border-slate-100 dark:border-slate-800 pt-6 space-y-4">
                {/* Compact Mode */}
                <div className="flex items-center justify-between py-1">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800 dark:text-white">Compact Layout Mode</h4>
                    <p className="text-[10px] font-semibold text-slate-400 mt-0.5">Reduces list item padding to fit more case records on screen.</p>
                  </div>
                  <button 
                    onClick={() => handleToggle('general', 'compactMode', generalSettings.compactMode === true)}
                    className={`w-10 h-5 rounded-full p-0.5 transition-all duration-300 ${generalSettings.compactMode === true ? 'bg-[#C8A34D]' : 'bg-slate-300 dark:bg-slate-700'}`}
                  >
                    <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 ${generalSettings.compactMode === true ? 'translate-x-5' : 'translate-x-0'}`} />
                  </button>
                </div>
              </div>

              {/* Accent Color Display */}
              <div className="border-t border-slate-100 dark:border-slate-800 pt-6">
                <label className="text-[10px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-3">Accent Brand Theme</label>
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-[#C8A34D] border border-[#C8A34D]/30 shadow-xs flex items-center justify-center text-[#111111] font-black text-xs">✓</div>
                  <p className="text-[11px] font-semibold text-slate-500 dark:text-slate-400">AI LEGAL Premium Gold theme is active across all advocate toolbars and counsel widgets.</p>
                </div>
              </div>
            </div>
          )}

          {/* CATEGORY 3: NOTIFICATIONS SETTINGS */}
          {activeCategory === 'notifications' && (
            <div className="space-y-6 animate-fade-in">
              <div>
                <h3 className="text-xs font-black uppercase tracking-widest text-[#C8A34D] border-b border-slate-100 dark:border-slate-800 pb-3 flex items-center gap-2">
                  <Bell size={14} /> Notification & Alert Preferences
                </h3>
                <p className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 mt-2">Manage court hearing alerts, daily cause list reminders, and AI generation completion notifications.</p>
              </div>

              <div className="space-y-4 pt-2">
                {/* Push Notifications */}
                <div className="flex items-center justify-between py-1">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800 dark:text-white">Push Notifications</h4>
                    <p className="text-[10px] font-semibold text-slate-400 mt-0.5">Receive alert notifications inside the browser workspace.</p>
                  </div>
                  <button 
                    onClick={() => handleToggle('notifications', 'pushNotif', notifPrefs.pushNotif !== false)}
                    className={`w-10 h-5 rounded-full p-0.5 transition-all duration-300 ${notifPrefs.pushNotif !== false ? 'bg-[#C8A34D]' : 'bg-slate-300 dark:bg-slate-700'}`}
                  >
                    <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 ${notifPrefs.pushNotif !== false ? 'translate-x-5' : 'translate-x-0'}`} />
                  </button>
                </div>

                {/* Email Notifications */}
                <div className="flex items-center justify-between py-1">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800 dark:text-white">Email Notifications</h4>
                    <p className="text-[10px] font-semibold text-slate-400 mt-0.5">Receive daily hearing schedules sent directly to your email inbox.</p>
                  </div>
                  <button 
                    onClick={() => handleToggle('notifications', 'emailNotif', notifPrefs.emailNotif !== false)}
                    className={`w-10 h-5 rounded-full p-0.5 transition-all duration-300 ${notifPrefs.emailNotif !== false ? 'bg-[#C8A34D]' : 'bg-slate-300 dark:bg-slate-700'}`}
                  >
                    <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 ${notifPrefs.emailNotif !== false ? 'translate-x-5' : 'translate-x-0'}`} />
                  </button>
                </div>

                {/* Court Hearing Reminders */}
                <div className="flex items-center justify-between py-1 border-t border-slate-100 dark:border-slate-800 pt-4">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800 dark:text-white">24-Hour Court Hearing Reminder</h4>
                    <p className="text-[10px] font-semibold text-slate-400 mt-0.5">Remind me 24 hours prior to scheduled Court Diary hearings.</p>
                  </div>
                  <button 
                    onClick={() => handleToggle('notifications', 'hearingReminder', notifPrefs.hearingReminder !== false)}
                    className={`w-10 h-5 rounded-full p-0.5 transition-all duration-300 ${notifPrefs.hearingReminder !== false ? 'bg-[#C8A34D]' : 'bg-slate-300 dark:bg-slate-700'}`}
                  >
                    <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 ${notifPrefs.hearingReminder !== false ? 'translate-x-5' : 'translate-x-0'}`} />
                  </button>
                </div>

                {/* Draft Completed */}
                <div className="flex items-center justify-between py-1">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800 dark:text-white">AI Draft Completion Alerts</h4>
                    <p className="text-[10px] font-semibold text-slate-400 mt-0.5">Notify me when background legal document generation completes.</p>
                  </div>
                  <button 
                    onClick={() => handleToggle('notifications', 'draftCompleted', notifPrefs.draftCompleted !== false)}
                    className={`w-10 h-5 rounded-full p-0.5 transition-all duration-300 ${notifPrefs.draftCompleted !== false ? 'bg-[#C8A34D]' : 'bg-slate-300 dark:bg-slate-700'}`}
                  >
                    <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 ${notifPrefs.draftCompleted !== false ? 'translate-x-5' : 'translate-x-0'}`} />
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* CATEGORY 4: SECURITY SETTINGS */}
          {activeCategory === 'security' && (
            <div className="space-y-8 animate-fade-in">
              <div>
                <h3 className="text-xs font-black uppercase tracking-widest text-[#C8A34D] border-b border-slate-100 dark:border-slate-800 pb-3 flex items-center gap-2">
                  <Shield size={14} /> Security & Account Access
                </h3>
                <p className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 mt-2">Manage verification credentials, passwords, and trusted devices.</p>
              </div>

              {/* Password change form */}
              <form onSubmit={handleUpdatePassword} className="space-y-4 bg-slate-50/50 dark:bg-[#0F172A] border border-slate-200/80 dark:border-slate-800 rounded-2xl p-6">
                <span className="text-[10px] font-black uppercase tracking-widest text-[#C8A34D] block mb-2">Change Account Password</span>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="text-[9px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1">Current Password</label>
                    <input
                      type="password"
                      placeholder="••••••••"
                      value={passwordForm.currentPassword}
                      onChange={(e) => setPasswordForm({ ...passwordForm, currentPassword: e.target.value })}
                      className="w-full bg-white dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2 text-xs font-bold focus:outline-none focus:border-[#C8A34D]"
                    />
                  </div>
                  <div>
                    <label className="text-[9px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1">New Password</label>
                    <input
                      type="password"
                      placeholder="••••••••"
                      value={passwordForm.newPassword}
                      onChange={(e) => setPasswordForm({ ...passwordForm, newPassword: e.target.value })}
                      className="w-full bg-white dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2 text-xs font-bold focus:outline-none focus:border-[#C8A34D]"
                    />
                  </div>
                  <div>
                    <label className="text-[9px] font-black text-slate-400 dark:text-slate-400 uppercase tracking-widest block mb-1">Confirm New Password</label>
                    <input
                      type="password"
                      placeholder="••••••••"
                      value={passwordForm.confirmPassword}
                      onChange={(e) => setPasswordForm({ ...passwordForm, confirmPassword: e.target.value })}
                      className="w-full bg-white dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2 text-xs font-bold focus:outline-none focus:border-[#C8A34D]"
                    />
                  </div>
                </div>
                <div className="flex justify-end pt-2">
                  <button
                    type="submit"
                    className="px-5 py-2.5 bg-[#C8A34D] hover:bg-[#b08d3b] text-[#111111] font-black rounded-xl text-xs uppercase tracking-wider transition-colors shadow-md cursor-pointer"
                  >
                    Update Password
                  </button>
                </div>
              </form>

              {/* Toggles */}
              <div className="space-y-4">
                {/* 2FA */}
                <div className="flex items-center justify-between py-1">
                  <div>
                    <h4 className="text-xs font-bold text-slate-800 dark:text-white">Two-Factor Authentication (2FA)</h4>
                    <p className="text-[10px] font-semibold text-slate-400 mt-0.5">Require an authentication code when logging in from new browsers.</p>
                  </div>
                  <button 
                    onClick={() => {
                      const next = !twoFactor;
                      setTwoFactor(next);
                      updatePersonalization('security', { twoFactor: next });
                      toast.success(next ? 'Two-Factor Authentication Enabled!' : 'Two-Factor Authentication Disabled.');
                    }}
                    className={`w-10 h-5 rounded-full p-0.5 transition-all duration-300 ${twoFactor ? 'bg-[#C8A34D]' : 'bg-slate-300 dark:bg-slate-700'}`}
                  >
                    <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-300 ${twoFactor ? 'translate-x-5' : 'translate-x-0'}`} />
                  </button>
                </div>

                {/* Sessions */}
                <div className="border-t border-slate-100 dark:border-slate-800 pt-6 space-y-4">
                  <span className="text-[10px] font-black uppercase tracking-widest text-[#C8A34D] block">Active Sessions & Trusted Devices</span>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="p-4 border border-slate-200 dark:border-slate-800 rounded-xl bg-slate-50/50 dark:bg-[#0F172A] flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <Laptop className="w-5 h-5 text-[#C8A34D]" />
                        <div>
                          <p className="text-xs font-bold text-slate-800 dark:text-white">Web App Terminal</p>
                          <p className="text-[10px] font-semibold text-slate-400">Active Now • Current Session</p>
                        </div>
                      </div>
                      <span className="px-2.5 py-0.5 bg-[#C8A34D]/15 border border-[#C8A34D]/30 text-[#B48A35] dark:text-[#C8A34D] rounded-md text-[9px] font-black uppercase tracking-widest">Active</span>
                    </div>

                    <div className="p-4 border border-slate-200 dark:border-slate-800 rounded-xl bg-slate-50/50 dark:bg-[#0F172A] flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <Smartphone className="w-5 h-5 text-slate-400" />
                        <div>
                          <p className="text-xs font-bold text-slate-800 dark:text-white">Android / iOS Mobile Terminal</p>
                          <p className="text-[10px] font-semibold text-slate-400">Mobile App Active</p>
                        </div>
                      </div>
                      <button onClick={() => toast.success('Signed out of mobile app session.')} className="text-[9px] font-black text-rose-500 uppercase tracking-wider hover:underline">Revoke</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* CATEGORY 5: HELP & APP GUIDE (MOBILE ANALYZED INTEGRATION) */}
          {activeCategory === 'help' && (
            <div className="space-y-6 animate-fade-in">
              <div>
                <h3 className="text-xs font-black uppercase tracking-widest text-[#C8A34D] border-b border-slate-100 dark:border-slate-800 pb-3 flex items-center gap-2">
                  <HelpCircle size={14} /> Help, Support & Interactive App Guide
                </h3>
                <p className="text-[11px] font-semibold text-slate-500 dark:text-slate-400 mt-2">Explore the interactive App Guide, view FAQs, report bugs, or contact customer support.</p>
              </div>

              {/* Sub-Navigation Tabs */}
              <div className="flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-3 overflow-x-auto custom-scrollbar">
                {[
                  { id: 'guide', label: '📖 App Guide AI', icon: BookOpen },
                  { id: 'faqs', label: '❓ FAQs & Knowledge Base', icon: HelpCircle },
                  { id: 'bug', label: '🐞 Report a Bug', icon: Bug },
                  { id: 'feature', label: '💡 Request Feature', icon: Sparkles },
                  { id: 'contact', label: '📞 Contact Support', icon: MessageSquare }
                ].map(tab => (
                  <button
                    key={tab.id}
                    onClick={() => setHelpSubTab(tab.id)}
                    className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer border ${
                      helpSubTab === tab.id
                        ? 'bg-[#C8A34D] border-[#C8A34D] text-[#111111] font-black shadow-xs'
                        : 'bg-slate-50 dark:bg-[#0F172A] border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white'
                    }`}
                  >
                    {tab.label}
                  </button>
                ))}
              </div>

              {/* SUB-TAB 1: APP GUIDE AI */}
              {helpSubTab === 'guide' && (
                <div className="space-y-6 animate-fade-in">
                  
                  {/* Interactive Quick Guide Topics */}
                  <div className="space-y-3">
                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-400 dark:text-slate-400 block">Featured Feature Guides</span>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {GUIDE_TOPICS.map(topic => {
                        const Icon = topic.icon;
                        const isSelected = selectedGuideTopic.id === topic.id;
                        return (
                          <div
                            key={topic.id}
                            onClick={() => setSelectedGuideTopic(topic)}
                            className={`p-4 rounded-2xl border transition-all cursor-pointer ${
                              isSelected 
                                ? 'bg-[#C8A34D]/10 border-[#C8A34D] dark:bg-[#C8A34D]/15'
                                : 'bg-slate-50/50 dark:bg-[#0F172A] border-slate-200/70 dark:border-slate-800 hover:border-[#C8A34D]/50'
                            }`}
                          >
                            <div className="flex items-center gap-3 mb-2">
                              <div className="w-8 h-8 rounded-xl bg-[#C8A34D]/15 border border-[#C8A34D]/30 flex items-center justify-center text-[#C8A34D]">
                                <Icon size={16} />
                              </div>
                              <h4 className="text-xs font-black text-slate-800 dark:text-white">{topic.title}</h4>
                            </div>
                            <p className="text-[11px] font-medium text-slate-500 dark:text-slate-400 leading-relaxed">{topic.summary}</p>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                  {/* Selected Topic Walkthrough */}
                  <div className="bg-slate-50/70 dark:bg-[#0F172A] border border-slate-200/80 dark:border-slate-800 rounded-2xl p-6 space-y-4">
                    <div className="flex items-center gap-2 text-[#C8A34D]">
                      <BookOpen size={16} />
                      <h4 className="text-xs font-black uppercase tracking-widest">{selectedGuideTopic.title} Walkthrough</h4>
                    </div>
                    <ol className="space-y-2.5">
                      {selectedGuideTopic.steps.map((step, idx) => (
                        <li key={idx} className="flex items-start gap-3 text-xs font-medium text-slate-700 dark:text-slate-300">
                          <span className="w-5 h-5 rounded-full bg-[#C8A34D]/20 text-[#B48A35] dark:text-[#C8A34D] font-black text-[10px] flex items-center justify-center shrink-0 mt-0.5">{idx + 1}</span>
                          <span>{step}</span>
                        </li>
                      ))}
                    </ol>
                  </div>

                  {/* Interactive App Guide AI Assistant Box */}
                  <div className="border border-slate-200 dark:border-slate-800 rounded-2xl p-6 bg-white dark:bg-[#1E293B] space-y-4">
                    <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
                      <div className="flex items-center gap-2 text-[#C8A34D]">
                        <Sparkles size={16} />
                        <span className="text-xs font-black uppercase tracking-widest">Ask App Guide AI Assistant</span>
                      </div>
                      <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">Interactive Assistance</span>
                    </div>

                    {/* Chat Messages */}
                    <div className="space-y-3 max-h-56 overflow-y-auto custom-scrollbar p-2">
                      {guideChat.map((msg, i) => (
                        <div key={i} className={`flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                          <div className={`max-w-[85%] rounded-2xl px-4 py-2.5 text-xs font-medium ${
                            msg.sender === 'user'
                              ? 'bg-[#C8A34D] text-[#111111] font-bold'
                              : 'bg-slate-100 dark:bg-[#0F172A] text-slate-800 dark:text-slate-200 border border-slate-200/60 dark:border-slate-800'
                          }`}>
                            {msg.text}
                          </div>
                        </div>
                      ))}
                      {isGuideThinking && (
                        <div className="flex justify-start">
                          <div className="bg-slate-100 dark:bg-[#0F172A] text-slate-400 px-4 py-2 rounded-2xl text-xs italic animate-pulse">
                            App Guide AI is formulating instructions...
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Quick Chip Triggers */}
                    <div className="flex flex-wrap gap-2 pt-2">
                      {[
                        'How to draft a legal notice?',
                        'How to analyze evidence OCR?',
                        'How to set up hearing reminders?',
                        'How to switch to dark mode?'
                      ].map(chip => (
                        <button
                          key={chip}
                          onClick={() => handleSendGuideMessage(chip)}
                          className="px-3 py-1 rounded-full bg-slate-100 dark:bg-[#0F172A] hover:bg-[#C8A34D]/20 text-[10px] font-bold text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700 transition-colors cursor-pointer"
                        >
                          {chip}
                        </button>
                      ))}
                    </div>

                    {/* Chat Input */}
                    <div className="flex items-center gap-2 pt-2">
                      <input
                        type="text"
                        value={guideQuery}
                        onChange={(e) => setGuideQuery(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && handleSendGuideMessage()}
                        placeholder="Type how to use any feature in AI LEGAL..."
                        className="flex-1 bg-slate-50 dark:bg-[#0F172A] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-medium focus:outline-none focus:border-[#C8A34D]"
                      />
                      <button
                        onClick={() => handleSendGuideMessage()}
                        className="px-4 py-2.5 bg-[#C8A34D] hover:bg-[#b08d3b] text-[#111111] rounded-xl font-bold text-xs flex items-center gap-1.5 cursor-pointer shadow-xs"
                      >
                        <Send size={14} /> Send
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {/* SUB-TAB 2: FAQS */}
              {helpSubTab === 'faqs' && (
                <div className="space-y-4 animate-fade-in">
                  <div className="relative">
                    <Search className="absolute left-3.5 top-3 w-4 h-4 text-slate-400" />
                    <input
                      type="text"
                      placeholder="Search FAQs..."
                      value={faqSearch}
                      onChange={(e) => setFaqSearch(e.target.value)}
                      className="w-full pl-10 pr-4 py-2.5 border border-slate-200 dark:border-slate-700 rounded-xl text-xs font-bold bg-slate-50/50 dark:bg-[#0F172A] focus:outline-none focus:border-[#C8A34D]"
                    />
                  </div>

                  <div className="space-y-3">
                    {filteredFaqs.map((faq, index) => {
                      const isExpanded = expandedFaqIndex === index;
                      return (
                        <div
                          key={index}
                          className="border border-slate-200/80 dark:border-slate-800 rounded-2xl bg-slate-50/30 dark:bg-[#0F172A] overflow-hidden transition-colors"
                        >
                          <button
                            onClick={() => setExpandedFaqIndex(isExpanded ? null : index)}
                            className="w-full p-4 flex items-center justify-between text-left cursor-pointer"
                          >
                            <div className="space-y-0.5">
                              <span className="text-[9px] font-black uppercase tracking-widest text-[#C8A34D] block">{faq.category}</span>
                              <h4 className="text-xs font-bold text-slate-800 dark:text-white">{faq.question}</h4>
                            </div>
                            <ChevronDown size={16} className={`text-slate-400 transition-transform ${isExpanded ? 'rotate-180 text-[#C8A34D]' : ''}`} />
                          </button>
                          {isExpanded && (
                            <div className="px-4 pb-4 pt-1 text-xs font-medium text-slate-600 dark:text-slate-300 border-t border-slate-100 dark:border-slate-800/60 leading-relaxed">
                              {faq.answer}
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* SUB-TAB 3: REPORT A BUG */}
              {helpSubTab === 'bug' && (
                <form onSubmit={handleBugSubmit} className="space-y-5 animate-fade-in bg-slate-50/50 dark:bg-[#0F172A] border border-slate-200/80 dark:border-slate-800 rounded-2xl p-6">
                  <div className="flex items-center gap-2 text-rose-500">
                    <Bug size={16} />
                    <h4 className="text-xs font-black uppercase tracking-widest">Report an Issue / Bug</h4>
                  </div>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-1">Issue Title</label>
                      <input
                        type="text"
                        value={bugForm.title}
                        onChange={(e) => setBugForm({ ...bugForm, title: e.target.value })}
                        placeholder="Brief summary of the issue..."
                        className="w-full bg-white dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D]"
                      />
                    </div>

                    <div>
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-1">Affected Tool / Page</label>
                      <select
                        value={bugForm.tool}
                        onChange={(e) => setBugForm({ ...bugForm, tool: e.target.value })}
                        className="w-full bg-white dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D] cursor-pointer"
                      >
                        <option value="General App">General App / Workspace</option>
                        <option value="AI Assistant">AI Assistant Chat</option>
                        <option value="Draft Drafter">Legal Notice & Drafter</option>
                        <option value="Evidence Analyst">Evidence Analyst & OCR</option>
                        <option value="Court Diary">Court Diary & Hearings</option>
                      </select>
                    </div>

                    <div>
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-1">Detailed Description</label>
                      <textarea
                        rows={4}
                        value={bugForm.description}
                        onChange={(e) => setBugForm({ ...bugForm, description: e.target.value })}
                        placeholder="Describe what happened, error message, or steps to reproduce..."
                        className="w-full bg-white dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-3 text-xs font-medium focus:outline-none focus:border-[#C8A34D] resize-none"
                      />
                    </div>
                  </div>

                  <div className="flex justify-end pt-2">
                    <button
                      type="submit"
                      disabled={submittingBug}
                      className="px-6 py-2.5 bg-rose-500 hover:bg-rose-600 text-white rounded-xl text-xs font-black uppercase tracking-wider transition-colors shadow-md cursor-pointer disabled:opacity-50"
                    >
                      {submittingBug ? 'Submitting...' : 'Submit Bug Report'}
                    </button>
                  </div>
                </form>
              )}

              {/* SUB-TAB 4: FEATURE REQUEST */}
              {helpSubTab === 'feature' && (
                <form onSubmit={handleFeatureSubmit} className="space-y-5 animate-fade-in bg-slate-50/50 dark:bg-[#0F172A] border border-slate-200/80 dark:border-slate-800 rounded-2xl p-6">
                  <div className="flex items-center gap-2 text-[#C8A34D]">
                    <Sparkles size={16} />
                    <h4 className="text-xs font-black uppercase tracking-widest">Submit Feature Idea</h4>
                  </div>
                  
                  <div className="space-y-4">
                    <div>
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-1">Feature Title</label>
                      <input
                        type="text"
                        value={featureForm.title}
                        onChange={(e) => setFeatureForm({ ...featureForm, title: e.target.value })}
                        placeholder="Name of requested feature..."
                        className="w-full bg-white dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-2.5 text-xs font-bold focus:outline-none focus:border-[#C8A34D]"
                      />
                    </div>

                    <div>
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-1">Feature Description</label>
                      <textarea
                        rows={3}
                        value={featureForm.description}
                        onChange={(e) => setFeatureForm({ ...featureForm, description: e.target.value })}
                        placeholder="Describe the functionality you'd like to see..."
                        className="w-full bg-white dark:bg-[#1E293B] border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white rounded-xl px-4 py-3 text-xs font-medium focus:outline-none focus:border-[#C8A34D] resize-none"
                      />
                    </div>
                  </div>

                  <div className="flex justify-end pt-2">
                    <button
                      type="submit"
                      disabled={submittingFeature}
                      className="px-6 py-2.5 bg-[#C8A34D] hover:bg-[#b08d3b] text-[#111111] rounded-xl text-xs font-black uppercase tracking-wider transition-colors shadow-md cursor-pointer disabled:opacity-50"
                    >
                      {submittingFeature ? 'Sending...' : 'Submit Idea'}
                    </button>
                  </div>
                </form>
              )}

              {/* SUB-TAB 5: CONTACT SUPPORT */}
              {helpSubTab === 'contact' && (
                <div className="space-y-6 animate-fade-in">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <a
                      href="mailto:support@ai-legal.in"
                      className="p-6 border border-slate-200/80 dark:border-slate-800 rounded-2xl bg-slate-50/50 dark:bg-[#0F172A] hover:border-[#C8A34D] transition-colors group"
                    >
                      <div className="flex items-center gap-3 mb-2">
                        <div className="w-10 h-10 rounded-xl bg-[#C8A34D]/15 border border-[#C8A34D]/30 flex items-center justify-center text-[#C8A34D]">
                          <Mail size={20} />
                        </div>
                        <div>
                          <h4 className="text-xs font-black text-slate-800 dark:text-white">Email Advocate Support</h4>
                          <span className="text-[10px] font-extrabold text-[#C8A34D]">support@ai-legal.in</span>
                        </div>
                      </div>
                      <p className="text-[11px] font-semibold text-slate-400">Direct technical & billing query line. Guaranteed response within 1 hour.</p>
                    </a>

                    <a
                      href="https://wa.me/919876543210"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="p-6 border border-slate-200/80 dark:border-slate-800 rounded-2xl bg-slate-50/50 dark:bg-[#0F172A] hover:border-emerald-500 transition-colors group"
                    >
                      <div className="flex items-center gap-3 mb-2">
                        <div className="w-10 h-10 rounded-xl bg-emerald-500/15 border border-emerald-500/30 flex items-center justify-center text-emerald-500">
                          <MessageCircle size={20} />
                        </div>
                        <div>
                          <h4 className="text-xs font-black text-slate-800 dark:text-white">WhatsApp Helpline</h4>
                          <span className="text-[10px] font-extrabold text-emerald-500">+91 98765 43210</span>
                        </div>
                      </div>
                      <p className="text-[11px] font-semibold text-slate-400">Instant WhatsApp support desk for practicing Advocates and Law Firms.</p>
                    </a>
                  </div>
                </div>
              )}

              {/* Version Footer */}
              <div className="border-t border-slate-100 dark:border-slate-800 pt-6 flex justify-between items-center text-[10px] font-bold text-slate-400">
                <span>AI Legal™ Platform Version v1.2.0</span>
                <span>Licensed for Advocates & Judiciary</span>
              </div>
            </div>
          )}

        </div>
      </div>

      {/* Confirmation Dialog Overlay */}
      <AnimatePresence>
        {dialogConfig.show && (
          <div className="fixed inset-0 z-[10000] flex items-center justify-center pointer-events-auto p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setDialogConfig({ show: false, type: '', title: '', desc: '', action: null })}
              className="fixed inset-0 bg-black/60 backdrop-blur-xs"
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="relative w-full max-w-sm bg-white dark:bg-[#1E293B] rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-800 p-6 z-10 text-center font-sans space-y-5 text-slate-900 dark:text-white"
            >
              <div className="w-12 h-12 rounded-full bg-amber-50 dark:bg-amber-950/40 text-amber-500 flex items-center justify-center mx-auto">
                <AlertTriangle size={22} />
              </div>
              <div className="space-y-2">
                <h3 className="text-base font-extrabold tracking-tight">{dialogConfig.title}</h3>
                <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 leading-relaxed px-2">
                  {dialogConfig.desc}
                </p>
              </div>
              <div className="flex gap-3 pt-2">
                <button
                  onClick={() => setDialogConfig({ show: false, type: '', title: '', desc: '', action: null })}
                  className="flex-1 py-2.5 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 rounded-xl text-xs font-black uppercase tracking-wider transition-all cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  onClick={dialogConfig.action}
                  className="flex-1 py-2.5 bg-[#C8A34D] hover:bg-[#b08d3b] text-[#111111] rounded-xl text-xs font-black uppercase tracking-wider transition-all shadow-md cursor-pointer"
                >
                  Confirm
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default SettingsPage;
